# Generated by Django 3.2.7 on 2022-02-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('patient', 'reason')},
        ),
    ]
